const candidates = [
  {
    id: 1,
    selected: false,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: true,
    isEU: false,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN', 'BCS'],
    region: 'Other city',
    start: 6,
    confirmed: true,
  },
  {
    id: 2,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 3,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 4,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 5,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 6,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 7,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 8,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 9,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 10,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 11,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 12,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 13,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 14,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 15,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 16,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 17,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 18,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 19,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
  {
    id: 20,
    selected: true,
    name: "A****** R***********",
    email: "a********@email.com",
    detailed: false,
    isEU: true,
    country: "Ukraine",
    age: 34,
    education: "Bachelor degree",
    experience: "Cooker",
    duration: 3,
    languages: ['DE', 'EN'],
    region: 'Other city',
    start: 6,
    confirmed: false,
  },
]

export default candidates;